"""add billing columns to buckets

Revision ID: 62bdcc5fcf88
Revises: 2afc803157ba
Create Date: 2026-04-19 15:21:48.606300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bdcc5fcf88'
down_revision: Union[str, Sequence[str], None] = '2afc803157ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_storage_bytes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ingress_bytes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('egress_bytes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('internal_transfer_bytes', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.drop_column('internal_transfer_bytes')
        batch_op.drop_column('egress_bytes')
        batch_op.drop_column('ingress_bytes')
        batch_op.drop_column('current_storage_bytes')

    # ### end Alembic commands ###
