"""add request count columns to buckets

Revision ID: aa2a0c0c2f8b
Revises: 00d8c1486f53
Create Date: 2026-04-19 15:39:49.168765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2a0c0c2f8b'
down_revision: Union[str, Sequence[str], None] = '00d8c1486f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_write_requests', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('count_read_requests', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.drop_column('count_read_requests')
        batch_op.drop_column('count_write_requests')

    # ### end Alembic commands ###
